### ISSUE TITLE
_matchingData not selected

### ISSUE THREAD

**Issue by mbglytch** [nojimage/cakephp-remember-me#1]
In CookieAuthenticate::findUserAndTokenBySeries $user->_matchingData is not present in the result of the query.

In my app i use a custom finder to find the user. In this finder i use query builder to select only what i need.
` $query->select(['id', 'email', 'password', 'role', 'member_id', 'is_secret', 'secret'])`

I fixed this using another custom finder for RememberMe.Cookie Auth specifying this.
`$query->select(TableRegistry::get('RememberMe.RememberMeTokens'))`

Maybe you can add this to CookieAuthenticate::findUserAndTokenBySeries line 260
`$query->select($this->getTokensTable())`

**Comment by nojimage** [comment]
@mbglytch Fixed this problem. Please update plugin and try it.
And thank you for the report!

**Comment by mbglytch** [comment]
I updated the plugin and it works like a charm !
