### ISSUE TITLE
Remember me not working

### ISSUE THREAD

**Issue by nickyvanurk** [nojimage/cakephp-remember-me#14]
Hi there, I am looking for some guidance. I have a website that uses the tinyauth plugin. I expect everything to work the same. This is some of my code:

```
$this->loadComponent('TinyAuth.Auth', [
            'autoClearCache' => true,
            'authorize' => [
                'TinyAuth.Tiny' => [
                   'roleColumn' => 'role_id',
                   'rolesTable' => 'Roles',
                ]
            ],
            'authenticate' => [
                'RememberMe.Cookie' => [
                    'userModel' => 'Users',
                    'fields' => ['username' => 'email', 'password' => 'password'],
                    'inputKey' => 'remember_me',
                    'cookie' => [
                        'name' => 'rememberMe',
                        'expires' => '+90 days',
                        'secure' => true,
                        'httpOnly' => true,
                    ],
                ],
                'Form' => [
                    'fields' => ['username' => 'email', 'password' => 'password'],
                    'finder' => 'auth'
                ],
            ],
            'loginAction' =>[
                'controller' => 'Login',
                'action' => 'index',
                'prefix'    => false,
                'plugin' => false
            ],
            'authError' => __('Log in to access this page.'),
            'logoutRedirect' => [
                'controller' => 'Login',
                'action' => 'index',
                'prefix'=> false,
                'plugin' => false
            ],
            'unauthorizedRedirect' => [
                'controller' => 'Login',
                'action' => 'index',
                'prefix'=> false,
                'plugin' => false
            ]
        ]);
```

A cookie gets set and is stored in the database. However after some time when my session has expired and return to the website I am logged out, even though the rememberMe cookie is still set. I am kinda out of ideas on how to fix it. Do you see any issues?

**Comment by nojimage** [comment]
I have never used TinyAuth, so I don't know the details.
The possibility is that there is not enough user data to be during authorize.

The `RememberMe.Cookie` setting seems to lack the `finder` option. Try the following:

```php
                'RememberMe.Cookie' => [
                    'userModel' => 'Users',
                    'fields' => ['username' => 'email', 'password' => 'password'],
                    'finder' => 'auth',
                    'inputKey' => 'remember_me',
                    'cookie' => [
                        'name' => 'rememberMe',
                        'expires' => '+90 days',
                        'secure' => true,
                        'httpOnly' => true,
                    ],
                ],
```

**Comment by nickyvanurk** [comment]
Does the remember-me plugin automatically detect and read the cookie and authenticate? Or do I manually do that in a beforeFilter? I assumed it would read the cookie automatically. Adding the finder didn't work.

**Comment by nojimage** [comment]
Yes, the RememberMe.Cookie Authenticator is automatically processing cookie.
Is it impossible to authenticate even if you disable the `authorize` option?

**Comment by nickyvanurk** [comment]
It actually works! It doesn't log me in automatically but when I went to a location on the site that needs authentication, it worked. Any idea on how to make it so it logs the user in when they visit the site when the cookie is set?

**EDIT**

Got it working, in the beforeFilter I now check if the identity of the user is set ($this->Auth->identity()) and if it is, set the user. The plugin works great, it was a problem the way the application I am working on is implemented.
