### ISSUE TITLE
.Is this plugin not compatible to cakephp 4?

### ISSUE THREAD

**Issue by jayshris** [nojimage/cakephp-remember-me#15]
Is this plugin not compatible to cakephp 4? If yes then please help me for calephp 4 remember me functionality. Thanks in advance.

**Comment by nojimage** [comment]
This plugin not yet support CakePHP 4 🍓 . 

I'd like to support Cake 4 if I have time, but it's going to take a while.

**Comment by nojimage** [comment]
[CakeDC/Users Plugin](https://github.com/CakeDC/users) has Remember me feature.

If you are in a hurry, please consider using the CakeDC/Users plugin.

**Comment by nojimage** [comment]
CakePHP 4 for support is now available.

Please checkout:

`composer require nojimage/cakephp-remember-me:4.0.0-beta1`
