### ISSUE TITLE
Cookie not saved

### ISSUE THREAD

**Issue by Moutard3** [nojimage/cakephp-remember-me#6]
Hey, I just installed this plugin but I can't manage to make it work.

From what I manage to debug, `$this->setLoginTokenToCookie($authComponent->response, $user, $token);` is returning the cookie, but it's not set after login.

The token is well saved.

```PHP
$this->loadComponent('Auth', [
            'authorize' => 'Controller',
            'loginAction' => [
                'plugin' => null,
                'prefix' => false,
                'controller' => 'Users',
                'action' => 'login'
            ],
            'loginRedirect' => '/',
            'logoutRedirect' => '/',
            'authenticate' => [
                'RememberMe.Cookie' => [
                    'always' => true,
                ],
                'Form',
            ]
        ]);
```

**Comment by nojimage** [comment]
Are you using CakePHP 3.6?
In 3.6, cookies may not be set correctly due to some deprecated errors.

I beginning work to support 3.6.  Please wait for a while.

**Comment by Moutard3** [comment]
Okay thanks for the fast answer ;)

**Comment by nojimage** [comment]
v2.1.0 released. https://github.com/nojimage/cakephp-remember-me/releases/tag/v2.1.0
please check this.

**Comment by Moutard3** [comment]
It's still not saving the cookie :/

**Comment by Moutard3** [comment]
My bad, it is saved when using ssl.
